version: '3.8'

services:
  calculator:
    build:
      context: ./
    dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    volumes:
      :- usr/src/app
      :- usr:src/app/node_modules

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    netwrorks:
      - monitor-net



